--Stand 31.5.19
CREATE TABLE "NODES"(
	"node_ID" INTEGER not null primary key generated by default as IDENTITY,
	"stop_name" VARCHAR(200),
	"stop_lat" VARCHAR(100),
	"stop_long" VARCHAR(100),
    "coordinate" ST_POINT(4326)
);

CREATE COLUMN TABLE "EDGES"(
	"edge_id" INTEGER not null primary key generated by default as IDENTITY,
	"start" INTEGER NOT NULL,
	"end" INTEGER NOT NULL,
	"line" VARCHAR(10),
	"start_name" VARCHAR(200),
	"end_name" VARCHAR(200)
);

drop table nodes;	
drop table edges;

CREATE GRAPH WORKSPACE SHORTEST_ROUTES
  EDGE TABLE EDGES
    SOURCE COLUMN "start"
    TARGET COLUMN "end"
    KEY COLUMN "edge_id"
  VERTEX TABLE NODES
    KEY COLUMN "node_ID";

DROP GRAPH WORKSPACE "SHORTEST_ROUTES";


--select GET_SHORTEST_PATH_ONE_TO_ONE from "SHORTEST_ROUTES";