--Stand 31.5.19
CREATE TABLE "NODES"(
	"node_ID" INTEGER not null primary key generated by default as IDENTITY,
	"stop_name" VARCHAR(200),
	"stop_lat" VARCHAR(100),
	"stop_long" VARCHAR(100),
    "coordinate" ST_POINT(4326)
);

drop table nodes;

CREATE COLUMN TABLE "EDGES"(
	"edge_id" INTEGER not null primary key generated by default as IDENTITY,
	"start" INTEGER NOT NULL,
	"end" INTEGER NOT NULL,
	"line" VARCHAR(10)
);
	
drop table edges;
